services:
  mongodb:
    image: mongo
    container_name: mongodb_vives-bank
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_vives-bank:/data/db

  redis:
    image: 'bitnami/redis:latest'
    container_name: redis_cache
    ports:
      - "6379:6379"  
    environment:
      - REDIS_PASSWORD=password123  
    volumes:
      - redis_data:/bitnami/redis  
    restart: unless-stopped 

volumes:
  mongo_vives-bank:
    driver: local 
  redis_data:
    driver: local